name: pulse
description: Powerful, flexible, and modern state management for Flutter. Inspired by Cubit, with unique features for advanced use cases.
version: 0.1.0
repository: https://github.com/alimehdirazab/pulse.git
homepage: https://github.com/alimehdirazab/pulse

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # No assets or fonts by default
  # assets:
  # fonts:
